# Generated by Django 5.1.2 on 2024-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCozyLounge', '0003_aboutus_remove_product_b_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='b_price',
            field=models.DecimalField(decimal_places=2, max_digits=99999),
        ),
    ]
